# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clockr < Formula
  desc "AI-powered time-tracking CLI for Clockify"
  homepage "https://github.com/christopherklint97/clockr"
  version "0.2.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/christopherklint97/clockr/releases/download/v0.2.8/clockr_0.2.8_darwin_amd64.tar.gz"
      sha256 "537278cf44b77314295d6b69d5877b5ba3594791918f57aedece5d9cb2827d15"

      define_method(:install) do
        bin.install "clockr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/christopherklint97/clockr/releases/download/v0.2.8/clockr_0.2.8_darwin_arm64.tar.gz"
      sha256 "9bbeeb16573694671752a64e12d1df12a1548c59389700db81953dde2c57ea84"

      define_method(:install) do
        bin.install "clockr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/christopherklint97/clockr/releases/download/v0.2.8/clockr_0.2.8_linux_amd64.tar.gz"
      sha256 "a87085d7fe3f23ee4f55100d35841cd27f5abfb2a16ea6b6ad251b530d63008e"
      define_method(:install) do
        bin.install "clockr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/christopherklint97/clockr/releases/download/v0.2.8/clockr_0.2.8_linux_arm64.tar.gz"
      sha256 "67ac97243287037c14f6ac040896ee663fe66ccb42c5b7972d539cd05b62087c"
      define_method(:install) do
        bin.install "clockr"
      end
    end
  end
end
