# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clockr < Formula
  desc "AI-powered time-tracking CLI for Clockify"
  homepage "https://github.com/christopherklint97/clockr"
  version "0.2.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/christopherklint97/clockr/releases/download/v0.2.7/clockr_0.2.7_darwin_amd64.tar.gz"
      sha256 "a1f338ab7c52f812d17cc7af3b3a640bc9069aee7647b03713188a471373a485"

      define_method(:install) do
        bin.install "clockr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/christopherklint97/clockr/releases/download/v0.2.7/clockr_0.2.7_darwin_arm64.tar.gz"
      sha256 "2d54fb6f31c35bb157cfc9c8e43cf56843023b5234af1b19956eef58dd0ebdaa"

      define_method(:install) do
        bin.install "clockr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/christopherklint97/clockr/releases/download/v0.2.7/clockr_0.2.7_linux_amd64.tar.gz"
      sha256 "fb4c5f7dbefc98dd3592c5b683082c88d7655b5fce92356cce7274a7647c899c"
      define_method(:install) do
        bin.install "clockr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/christopherklint97/clockr/releases/download/v0.2.7/clockr_0.2.7_linux_arm64.tar.gz"
      sha256 "bb23a7265f99964aac18c723a01be14125fd8c2ed76e60748ab4b81560b128ab"
      define_method(:install) do
        bin.install "clockr"
      end
    end
  end
end
