# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Taxpilot < Formula
  desc "AI-assisted US tax filing CLI"
  homepage "https://github.com/christopherklint97/taxpilot"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/christopherklint97/taxpilot/releases/download/v0.1.0/taxpilot_0.1.0_darwin_amd64.tar.gz"
      sha256 "8cfb3e309217016282b55a8ce73a4a53e7f3c0b475d58a4d654d39d81b280b3d"

      define_method(:install) do
        bin.install "taxpilot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/christopherklint97/taxpilot/releases/download/v0.1.0/taxpilot_0.1.0_darwin_arm64.tar.gz"
      sha256 "2110ce4ac91e9697a5d2ed49dcaa38039a26f1f9414c807343bf2d276ec5abaf"

      define_method(:install) do
        bin.install "taxpilot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/christopherklint97/taxpilot/releases/download/v0.1.0/taxpilot_0.1.0_linux_amd64.tar.gz"
      sha256 "ff40e5fb53636628441daf94eca48a1975016c866ec6a00351176e3ecadf254f"
      define_method(:install) do
        bin.install "taxpilot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/christopherklint97/taxpilot/releases/download/v0.1.0/taxpilot_0.1.0_linux_arm64.tar.gz"
      sha256 "5735db2518e2892c4839ea307468d8d25da9ce1331bc1acd20b913b47e532983"
      define_method(:install) do
        bin.install "taxpilot"
      end
    end
  end
end
