# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Taxpilot < Formula
  desc "AI-assisted US tax filing CLI"
  homepage "https://github.com/christopherklint97/taxpilot"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/christopherklint97/taxpilot/releases/download/v0.1.2/taxpilot_0.1.2_darwin_amd64.tar.gz"
      sha256 "cadffb3ff39b666a3c324a1c9b7cdc6a37ae6d445b4ed8a7486ea3c542b003f6"

      define_method(:install) do
        bin.install "taxpilot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/christopherklint97/taxpilot/releases/download/v0.1.2/taxpilot_0.1.2_darwin_arm64.tar.gz"
      sha256 "c8d43d2a649f5e5f9ebd854742f20a1bbf9cec463d70f13d3d6669a421f2f61b"

      define_method(:install) do
        bin.install "taxpilot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/christopherklint97/taxpilot/releases/download/v0.1.2/taxpilot_0.1.2_linux_amd64.tar.gz"
      sha256 "b40f25fe20d75c042b9819574fcc753f6ee6c954160f362cb3b088b4b5a04e70"
      define_method(:install) do
        bin.install "taxpilot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/christopherklint97/taxpilot/releases/download/v0.1.2/taxpilot_0.1.2_linux_arm64.tar.gz"
      sha256 "efa10d5d8cf225b4bd6d96e08e27195fe6594183a701e14602befbedac8c16a4"
      define_method(:install) do
        bin.install "taxpilot"
      end
    end
  end
end
